"""empty message

Revision ID: 220b3bd6a57c
Revises: fc300210692f
Create Date: 2016-12-05 11:04:04.079387

"""

# revision identifiers, used by Alembic.
revision = '220b3bd6a57c'
down_revision = 'fc300210692f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.String(length=8), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone_number')
    ### end Alembic commands ###
