"""empty message

Revision ID: 353d01f94072
Revises: bb300afb7c74
Create Date: 2016-11-14 11:05:38.201428

"""

# revision identifiers, used by Alembic.
revision = '353d01f94072'
down_revision = 'bb300afb7c74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'pending', 'shipped', name='order_statuses'), nullable=False),
    sa.Column('customer_username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_username'], ['customer.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    ### end Alembic commands ###
