"""empty message

Revision ID: 69d7a2a016fb
Revises: 353d01f94072
Create Date: 2016-11-14 12:26:26.322926

"""

# revision identifiers, used by Alembic.
revision = '69d7a2a016fb'
down_revision = '353d01f94072'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_orders',
    sa.Column('book_ISBN', sa.String(length=13), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_ISBN'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_orders')
    ### end Alembic commands ###
