"""empty message

Revision ID: 6edec4b28fec
Revises: 353d01f94072
Create Date: 2016-11-16 00:56:31.653213

"""

# revision identifiers, used by Alembic.
revision = '6edec4b28fec'
down_revision = '353d01f94072'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=13), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'book_isbn')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_orders')
    ### end Alembic commands ###
