"""empty message

Revision ID: 71567015d02e
Revises: bb300afb7c74
Create Date: 2016-11-14 03:49:47.367464

"""

# revision identifiers, used by Alembic.
revision = '71567015d02e'
down_revision = 'bb300afb7c74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('customer_feedback', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('customer_review', sa.String(), nullable=False),
    sa.Column('ISBN', sa.String(length=13), nullable=False),
    sa.ForeignKeyConstraint(['customer_feedback'], ['customer.username'], ),
    sa.ForeignKeyConstraint(['customer_review', 'ISBN'], [u'review.username', u'review.ISBN'], ),
    sa.PrimaryKeyConstraint('customer_feedback', 'customer_review', 'ISBN'),
    sa.CheckConstraint('rating<=2 AND rating>=0', name='rating_between_0_and_2')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    ### end Alembic commands ###
