"""empty message

Revision ID: 969920050f85
Revises: e961d35a2ad0
Create Date: 2016-11-01 19:41:40.448428

"""

# revision identifiers, used by Alembic.
revision = '969920050f85'
down_revision = 'e961d35a2ad0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('ISBN', sa.String(length=13), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('year_of_publication', sa.SmallInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('format', sa.Enum('hardcover', 'softcover', name='formats'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('ISBN')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    ### end Alembic commands ###
