"""empty message

Revision ID: bb300afb7c74
Revises: 969920050f85
Create Date: 2016-11-07 04:15:22.671041

"""

# revision identifiers, used by Alembic.
revision = 'bb300afb7c74'
down_revision = '969920050f85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('ISBN', sa.String(length=13), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['book.ISBN'], ),
    sa.ForeignKeyConstraint(['username'], ['customer.username'], ),
    sa.PrimaryKeyConstraint('ISBN', 'username'),
    sa.CheckConstraint('score<=10 AND score>=0', name='score_between_0_and_10')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    ### end Alembic commands ###
