"""empty message

Revision ID: e961d35a2ad0
Revises: 4ee4a2ca9fab
Create Date: 2016-10-31 22:59:55.993423

"""

# revision identifiers, used by Alembic.
revision = 'e961d35a2ad0'
down_revision = '4ee4a2ca9fab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_manager',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_manager')
    ### end Alembic commands ###
