"""empty message

Revision ID: fc300210692f
Revises: 6edec4b28fec
Create Date: 2016-11-16 03:05:31.158129

"""

# revision identifiers, used by Alembic.
revision = 'fc300210692f'
down_revision = '6edec4b28fec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('customer_feedback', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('customer_review', sa.String(), nullable=False),
    sa.Column('ISBN', sa.String(length=13), nullable=False),
    sa.ForeignKeyConstraint(['customer_feedback'], ['customer.username'], ),
    sa.ForeignKeyConstraint(['customer_review', 'ISBN'], [u'review.username', u'review.ISBN'], ),
    sa.PrimaryKeyConstraint('customer_feedback', 'customer_review', 'ISBN')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    ### end Alembic commands ###
